# Generated by Django 6.1 on 2026-09-29 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', 'seed_catalog_20260915_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
    ]
